# Generated by cpp11: do not edit by hand

test_tidy_r_names <- function(x) {
  .Call(`_cpp11janitortest_test_tidy_r_names`, x)
}

test_tidy_r_vars <- function(x) {
  .Call(`_cpp11janitortest_test_tidy_r_vars`, x)
}
